# Generated by Django 5.0.3 on 2024-03-14 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo del automovil')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca del automovil')),
                ('color', models.CharField(max_length=100, verbose_name='Color del vehiculo')),
                ('año', models.IntegerField(max_length=100, verbose_name='año del modelo')),
            ],
        ),
    ]
