# Generated by Django 5.0.3 on 2024-03-14 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='año',
            field=models.IntegerField(verbose_name='año del modelo'),
        ),
        migrations.AlterModelTable(
            name='auto',
            table='Auto',
        ),
    ]
